#compose
version: '3.9'

services:
  app:
    container_name: rustapp
    image: ghcr.io/innotugrid/backend:main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${BACKEND_PORT}:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_DB_USER}:${POSTGRES_DB_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
    
  db:
    container_name: timescaledb
    image: 'timescale/timescaledb:latest-pg14'
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/timescaledb/data
      - ./initdb:/docker-entrypoint-initdb.d
  
volumes:
  pgdata: {}